# Generated by Django 4.1.4 on 2022-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert')], default='main', max_length=12)),
                ('preparation_time', models.PositiveIntegerField(help_text='in minutes')),
                ('cooking_time', models.PositiveIntegerField(help_text='in minutes')),
                ('serving', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('intermediate', 'Intermediate'), ('hard', 'Hard')], default='intermediate', max_length=12)),
                ('ingredients', models.CharField(max_length=240)),
                ('directions', models.CharField(max_length=240)),
                ('notes', models.CharField(max_length=240)),
            ],
        ),
    ]
